### ISSUE TITLE
patch for 2.4.1 API changes

### ISSUE THREAD

**Issue by GuillaumeAllegre** [justinhunt/moodle-assignsubmission_youtube#1]
Please apply this patch to conform to the 2.4.1 API changes. Thanks.

<pre>
--- a/mod/assign/submission/youtube/locallib.php
+++ b/mod/assign/submission/youtube/locallib.php
@@ -642,7 +642,7 @@ class assign_submission_youtube extends assign_submission_plugin {
      * @param stdClass $submission The submission
      * @return array - return an array of files indexed by filename
      */
-    public function get_files(stdClass $submission) {
+    public function get_files(stdClass $submission, stdClass $user) {
         $result = array();
        //how to handle this?
         return $result;
</pre>

**Comment by justinhunt** [comment]
Thanks I have made that change now. I also added a default value to the
$user param so that users still on old versions of Moodle won't get in
trouble.
I had the same issue with another assignment submission type (
https://moodle.org/mod/forum/discuss.php?d=224265  ), but didn't think to
change this one.

**Comment by justinhunt** [comment]
Fixed this a while back but forgot to close it.
